package me;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

public class LoginScreen {

    private JButton login;
    private JTextField userName;
    private JPasswordField password;
    private JRadioButton admin;
    private JRadioButton agent;
    private JRadioButton tenant;
    private javax.swing.JPanel JPanel;
    private JLabel errorMessage;
    private JButton registerInsteadButton;

    public static JFrame frame = new JFrame("Login");


    public LoginScreen() {
        admin.setSelected(true);
        userName.setText("skilroy0");
        password.setText("ZnmUfOo");


        login.addActionListener(e -> {

            try {
                if (admin.isSelected()) {
                    if (User.check(userName.getText(), password.getText(), User.ADMIN_PREFIX)) {
                        frame.setVisible(false);
                        AdminScreen.lunch();
                    } else {
                        errorMessage.setVisible(true);
                    }
                }
                if (agent.isSelected()) {
                    if (User.check(userName.getText(), password.getText(), User.AGENT_PREFIX)) {
                        frame.setVisible(false);
                        //TODO: CODE TO LUNCH AGENT SCREEN
                    } else {
                        errorMessage.setVisible(true);
                    }
                }
                if (tenant.isSelected()) {
                    if (User.check(userName.getText(), password.getText(), User.TENANT_PREFIX)) {
                        frame.setVisible(false);
                        //TODO: CODE TO LUNCH AGENT SCREEN
                    } else {
                        errorMessage.setVisible(true);
                    }
                }

            } catch (IOException ioException) {
                ioException.printStackTrace();
            }
        });

        resetRadioButton();

        registerInsteadButton.addActionListener(e -> {

        });
        registerInsteadButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    DetailsScreen.lunch(new User("", "", "", User.getNextId(User.AGENT_PREFIX), ""), DetailsScreen.REGISTER);
                } catch (IOException ioException) {
                    ioException.printStackTrace();
                }
            }
        });
    }

    public static void main(String[] args) {

        Global.setTheme();
        JFrame.setDefaultLookAndFeelDecorated(true);
        Dimension frameDimension = new Dimension(375, 200);

        frame.setContentPane(new LoginScreen().JPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setSize(frameDimension);
        frame.setMinimumSize(frameDimension);

    }

    private void resetRadioButton() {
        agent.addActionListener(e -> {
            admin.setSelected(false);
            tenant.setSelected(false);
        });
        admin.addActionListener(e -> {
            agent.setSelected(false);
            tenant.setSelected(false);
        });
        tenant.addActionListener(e -> {
                    admin.setSelected(false);
                    agent.setSelected(false);
                }
        );
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        JPanel = new JPanel();
        JPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Username");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Pasword");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel.add(label2, gbc);
        userName = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel.add(userName, gbc);
        admin = new JRadioButton();
        admin.setText("Admin");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        JPanel.add(admin, gbc);
        tenant = new JRadioButton();
        tenant.setText("Tenant");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        JPanel.add(tenant, gbc);
        agent = new JRadioButton();
        agent.setText("Agent");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        JPanel.add(agent, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Type");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel.add(label3, gbc);
        errorMessage = new JLabel();
        errorMessage.setText("username or password NOT correct");
        errorMessage.setVisible(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel.add(errorMessage, gbc);
        final javax.swing.JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel.add(panel1, gbc);
        registerInsteadButton = new JButton();
        registerInsteadButton.setText("Register Insted");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(registerInsteadButton, gbc);
        login = new JButton();
        login.setText("Login");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(login, gbc);
        final javax.swing.JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        password = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel.add(password, gbc);
        final javax.swing.JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel.add(spacer2, gbc);
        final javax.swing.JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel.add(spacer3, gbc);
        final javax.swing.JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel.add(spacer4, gbc);
        final javax.swing.JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel.add(spacer5, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return JPanel;
    }

}

