package me;

import javax.swing.*;
import java.awt.*;

public class TenantScreen {
    private JPanel jPanel;

    public static void lunch() {
        Dimension frameDimension = new Dimension(600, 400);
        JFrame frame = new JFrame("Tenant");
        frame.setContentPane(new TenantScreen().jPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(frameDimension);
        frame.setMinimumSize(frameDimension);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new GridBagLayout());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }
}
